# REF ~ https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-devices/-/blob/e21f0f0e/.gitlab-ci.yml

## Docker image: https://hub.docker.com/_/python
image: docker.io/python:3.7

stages:
  - linting
  - generate_documentation

.install_prerequesites_pip: &install_prerequesites_pip |
  pip install -r requirements.txt

.setup_for_html: &setup_for_html |
  apt-get update
  apt-get -y install pandoc

linting:
  stage: linting
  allow_failure: yes
  rules:
    - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - yamllint devices.yml

pages:
  stage: generate_documentation
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - *setup_for_html
    - python bin/generate_images_stats.py
    - python bin/generate_images_table.py
    #- python bin/generate_kernels_stats.py
    #- python bin/generate_kernels_table.py
    - mkdir -p public/
    - mv css/public.css public/
    - pandoc -s .gitlab/www.md -o public/index.html -c public.css
    - pandoc -s image-stats.md -o public/nethunter-image-stats.html -c public.css
    - pandoc -s images.md -o public/nethunter-images.html -c public.css
    #- pandoc -s md/kernel-stats.md -o public/nethunter-kernel-stats.html -c public.css
    #- pandoc -s md/kernels.md -o public/nethunter-kernels.html -c public.css
  artifacts:
    paths:
      - ./public
    expire_in: 1 week
