#!/bin/sh                                                                                                                                                                                                                                 
# Code comes from Fran Rodriguez
# https://github.com/FrangaL/rpi-img-builder
flock /dev/mmcblk0 sfdisk -f /dev/mmcblk0 -N 2 <<EOF
,+
EOF
 
sleep 5
udevadm settle
sleep 5
flock /dev/mmcblk0 partprobe /dev/mmcblk0
mount -o remount,rw /dev/mmcblk0p2
resize2fs /dev/mmcblk0p2
