#!/bin/sh
# Code comes from Francisco José Rodríguez Martos
# https://github.com/FrangaL/rpi-img-builder

root_dev="$(findmnt -n -o SOURCE /)"
root_part="/dev/$(lsblk -no pkname $root_dev)"
root_part_num=$(blkid -sPART_ENTRY_NUMBER -o value -p $root_part)

flock $root_part sfdisk -f $root_part -N $root_part_num <<EOF
,+
EOF

sleep 5
udevadm settle
sleep 5
flock $root_part partprobe $root_part
mount -o remount,rw $root_dev
resize2fs $root_dev
