#!/bin/bash -e

# Add the kali user and give them all the access they need.
if ! grep -qE '^kali:' /etc/passwd; then
    adduser kali --home /home/kali --shell /bin/bash --disabled-password --gecos "" 2>&1 >>/var/log/rootfs-cleanups.log

    mkdir -p /home/kali 2>&1 >>/var/log/rootfs-cleanups.log
    chown kali:kali /home/kali 2>&1 >>/var/log/rootfs-cleanups.log
    echo 'kali:kali' |chpasswd 2>&1 >>/var/log/rootfs-cleanups.log
fi

# Reload and trigger udev rule
udevadm control --reload-rules
udevadm trigger

if ! grep -qE '^bluetooth:' /etc/group; then
    groupadd -r -g 112 bluetooth
fi

if ! grep -qE '^lpadmin:' /etc/group; then
    groupadd -r -g 113 lpadmin
fi

if ! grep -qE '^scanner:' /etc/group; then
    groupadd -r -g 122 scanner
fi

KALI_GROUPS="adm audio bluetooth cdrom dialout dip games i2c input kali kismet lpadmin netdev plugdev render scanner staff sudo systemd-journal users video wireshark"

for i in $KALI_GROUPS; do
    echo "runonce: adding kali to $i" 2>&1 >>/var/log/rootfs-cleanups.log
        adduser kali $i 2>&1 >>/var/log/rootfs-cleanups.log
done
