#!/bin/bash -e

# Choose a locale and generate it to eliminate LC warnings.
LOCALES="en_US.UTF-8"
sed -i 's/^# *\($LOCALES\)/\1/' /etc/locale.gen
locale-gen
echo LANG=$LOCALES >/etc/locale.conf
echo LC_ALL=$LOCALES >>/etc/locale.conf
cat <<'EOM' >$R/etc/profile.d/default-lang.sh
if [ -z "$LANG" ]; then
    source /etc/locale.conf
    export LANG
elif [ -z "$LC_ALL" ]; then
    source /etc/locale.conf
    export LC_ALL
fi
EOM
