#!/bin/bash -e

# Choose a locale and generate it to eliminate LC warnings.
#echo en_US.UTF-8 UTF-8 >/etc/locale.gen
LOCALES="en_US.UTF-8 UTF-8"
sed -i 's/^# *\($LOCALES\)/\1/' /etc/locale.gen
locale-gen 2>&1 >> /var/log/rootfs-cleanups.log
echo LANG=en_US.UTF-8 >/etc/locale.conf
