#!/bin/bash
set -e

# Rebuild xfonts-base, ca-certificates and shared-mime-info database
rebuild="shared-mime-info xfonts-base ca-certificates"
for pkg in $rebuild; do
    if [[ $(dpkg -l $pkg | awk '/^ii/ { print $1 }') = ii ]]; then
        dpkg-reconfigure -fnoninteractive $pkg

    fi
done

# Clear and regenerate the font cache
if command -v fc-cache >/dev/null 2>&1; then
  fc-cache -f
fi

# Update shared MIME info database
if command -v update-mime-database >/dev/null 2>&1; then
  /usr/bin/update-mime-database /usr/share/mime
fi

# Update certificates
if command -v update-ca-certificates >/dev/null 2>&1; then
  /usr/sbin/update-ca-certificates
fi
# Regenerate the default snakeoil cert
if command -v make-ssl-cert >/dev/null 2>&1; then
make-ssl-cert generate-default-snakeoil --force-overwrite
fi
